
import SideNavigation from "@/components/UI/sideNavigation/SideNavigation";
import type { Metadata } from "next";
import { Montserrat } from 'next/font/google'
import './globalStyle.scss'

const mntserrat = Montserrat({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: "Concentration",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mntserrat.className}>
        <SideNavigation/>
        {children}
      </body>
    </html>
  );
}
